config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :requests, only: %i[index show new create destroy] do
    resources :rides, only: %i[create show]
  end

  resources :rides do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_one :ride, dependent: :destroy
  validates :starting_location, :ending_location, presence: true
  enum status: { confirmed: 0, pending: 1 }
  after_validation :geocode

  def geocode
    starting = Geocoder.search(starting_location).first
    ending = Geocoder.search(ending_location).first
    lat_start, long_start = [starting.latitude, starting.longitude]
    lat_end, long_end = [ending.latitude, ending.longitude]
    self.start_latitude = lat_start
    self.start_longitude = long_start
    self.end_latitude = lat_end
    self.end_longitude = long_end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :ride
  belongs_to :user
  validates :rating, inclusion: { in: 1..5 }
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
  belongs_to :request
  has_many :reviews
  validates :user, uniqueness: { scope: :request }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name nickname car phone_number])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  	@navbar_white = true
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_request, only: %i[show destroy]

  def index
    @requests = Request.pending
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    @request.user = current_user
    @request.status = "pending"
    if @request.save
      redirect_to request_path(@request)
    else
      render :new
    end
  end

  def show
    @coords = [
      [@request.start_longitude, @request.start_latitude],
      [@request.end_longitude, @request.end_latitude]
    ]
  end

  def destroy
    @request.destroy

    redirect_to new_request_path
  end

  private

  def set_request
    @request = Request.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:starting_location, :ending_location)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @ride = Ride.find(params[:ride_id])
  end

  def create
    @ride = Ride.find(params[:ride_id])
    @review = Review.new(review_params)
    @review.ride = @ride
    @review.user = current_user
    @ride.completed = true
    if @review.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def index
    @rides = Ride.all
  end

  def create
    @request = Request.find(params[:request_id])
    @ride = Ride.new
    @ride.request = @request
    @ride.user = current_user
    if @ride.save
      @request.confirmed!
      RequestChannel.broadcast_to(
        @request,
        render_to_string(partial: "shared/see_your_trips", locals: { request: @request })
      )
      redirect_to ride_path(@ride)
    else
      render 'requests/show'
    end
  end

  def update
    @ride = Ride.find(params[:id])
    if @ride.update(completed: true)
      RideChannel.broadcast_to(
        @ride,
        render_to_string(partial: "shared/journey_completed", locals: { ride: @ride })
      )
      redirect_to new_ride_review_path(@ride)
    end
  end

  def show
    @ride = Ride.find(params[:id])
    @coords = [
      [@ride.request.start_longitude, @ride.request.start_latitude],
      [@ride.request.end_longitude, @ride.request.end_latitude]
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetHome the safe way</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
     <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
     <%= render 'shared/ios_pwa_links' %>
     <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render 'shared/navbar' %></div>
      <div class="content-container"><%= yield %></div>
      <div class="footer-container"><%= render "shared/footer" %></div>
    </div>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://c0.wallpaperflare.com/preview/756/536/953/empty-street-with-lights-during-nighttime.jpg)">
  <div class="acontainerthree">
    
  <div class="frase">
    <!-- <p>Choose to get home:</p> -->
  </div>
   <div class="zz">
    <div class="status">
      <%=link_to "Passenger", new_request_path, class: "btn btn-outline-primary btn-lg btn-block" %>
    </div>


    <div class="status">
       <%= link_to "Driver", requests_path, class: "btn btn-outline-primary btn-lg btn-block"  %>
     </div>
   </div>

  </div>
</div>

<div class="intro">
    <h2>How does it work?</h2>
  </div>
    <div class="row remove-gutter">
    <div class="col-sm-4">
      <h5 style="text-align: center">
      <strong>1. REGISTER:</strong></h5>
      <p style="text-align: center">Register your personal and vehicle details to your GetHome account.</p>
    </div>
   <div class="col-sm-4">
      <h5 style="text-align: center">
      <strong>2. CHOOSE A STATUS:</strong></h5>
      <p style="text-align: center">Choose if you are a passenger that needs to be taken home or if you are one of our volunteer drivers.</p>
    </div>
    <div class="col-sm-4">
      <h5 style="text-align: center">
      <strong>3. GET HOME:</strong></h5>
      <p style="text-align: center">Enter your current location and your home address and be taken home by one of our trusted drivers.</p>
    </div>
  </div>

<div class="banner-2" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.pexels.com/photos/3459398/pexels-photo-3459398.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940)">
  <div id="quote">
    <h2 style="text-align: center">
      <strong>"When the fun is over, let us get you home"</strong></h2>
  </div>
</div>

  <div class="intro">
    <h2>Why choose GetHome?</h2>
  </div>

    <div class="row remove-gutter">
    <div class="col-sm-4">
      <h5 style="text-align: center">
        <strong>TRUSTED SERVICE</strong></h5>
          <p style="text-align: center">24/7 customer service</p>
          <p style="text-align: center">Fully comprehensive insurance for your car</p>
          <p style="text-align: center">Extensive background checks carried out on all our drivers</p>

    </div>
   <div class="col-sm-4">
      <h5 style="text-align: center">
        <strong>IT'S FREE</strong></h5>
          <p style="text-align: center">A free service</p>
          <p style="text-align: center">Drivers are volunteers</p>
          <p style="text-align: center">Subsidised by government</p>
    </div>
  <div class="col-sm-4">
      <h5 style="text-align: center">
        <strong>TRAVEL SAFETY</strong></h5>
          <p style="text-align: center">Ensure everyone gets home safely</p>
          <p style="text-align: center">Track your journey</p>
          <p style="text-align: center"> All drivers issued with ID cards to be sure you're riding with our trusted GetHome team</p>
    </div>
</div>

app/views/requests/index.html.erb
<div class="index margin-from-navbar">
	<h1 style="text-align: center">Requests</h1>
	
	</div>

	 <div class="destination">
	 	
		<% @requests.each do |request| %>
		   <div class="location">
				<h5>Pick-up location:</h5>
        <p><%= request.starting_location %></p>
				<h5>Destination:</h5>
        <p><%= request.ending_location %></p>
				<div class="details">
				<h5><%= link_to 'Details', request_path(request), class: "btn" %></h5>
				</div>
			</div>
		 <% end %>



		<br>
		
	 </div>
</div>

app/views/requests/new.html.erb
<div class="acontainer margin-from-navbar">


<%= simple_form_for(@request) do |f| %>
  <%= f.input :starting_location %>
  <%= f.input :ending_location %>
  <%= f.submit "Request Driver", class: "btn btn-info btn-block" %>
<% end %>
  <div class="lback text-center" >
     <%= link_to  root_path do %>
     <i class="fas fa-long-arrow-alt-left"></i> back
     <% end %>
  </div>

</div>

app/views/requests/show.html.erb
<div class="acontainertwo margin-from-navbar">

  <h2>Journey details</h2>

  <h5>Time of journey:</h5>
    <div id="instructions"></div>

  <h5>Pick-up location:</h5>
    <p><%= @request.starting_location %></p>

  <h5>Destination:</h5>
    <p><%= @request.ending_location %></p>

  <div id="map"
       style="width: 100%; height: 420px;"
       data-coords="<%= @coords.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="align-self-center" id="accept" data-request-id="<%= @request.id %>">
    <% if @request.user == current_user %>
      <%= "" %>
    <% else %>
      <br>
      <h4>Name of passenger:</h4>
        <h5><%= @request.user.first_name %> <%= @request.user.last_name %></h5>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star"></span>
        <br>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{@request.user.nickname}", id: "aavatar" %>
      <h5>Car:</h5>
        <p><%= @request.user.car %></p>
      <h5>Telephone number:</h5>
        <p><%= @request.user.phone_number %></p>
    <% end %>

    <% if @request.user == current_user %>
      <%= render 'shared/see_your_trips' %>
    <% else %>
        <%= link_to "Accept", request_rides_path(@request), method: "post", class: "btn btn-primary btn-lg btn-block" %>
    <div class="aback" >
      <%= link_to  requests_path do %>
        <i class="fas fa-long-arrow-alt-left"></i> back
      <% end %>
    </div>
    <% end %>
        <!-- <div class="float-left"><%#= link_to "Back", requests_path, class: "btn btn-secondary btn-lg" %></div> -->
  </div>
</div>

app/views/reviews/new.html.erb
<% if @ride.user == current_user %>


	<div class="container" id="ratings">
		<div class="row1">
			<div class="col-xs-4">
	      <%= simple_form_for [@ride, @review] do |f|%>
	        <p>  <%= f.input :rating, collection: (1..5).to_a, label: "Was the car in good shape?" %> </p>
	        <p><%= f.input :content, label: "Please take some time to describe your journey with the passenger:", as: :text %> </p>
	        <%= f.submit "Submit", class: "btn btn-primary btn-block laszlo" %>
	       <% end %>
			</div>
		</div>
	</div>

	<% else %>

	<div class="container" id="ratings">
		<div class="row1">
			<div class="col-xs-4">
	      <%= simple_form_for [@ride, @review] do |f|%>
	        <p><%= f.input :rating, collection: (1..5).to_a, label: "How was the driver's driving skills?" %></p>
	        <p><%= f.input :content, label: "Please take some time to describe the GetHome service:", as: :text %>  </p>
	        <%= f.submit "Submit", class: "btn btn-primary btn-block laszlo" %>
	       <% end %>
			</div>
    </div>
  </div>
<% end %>

app/views/reviews/reviews.html.erb
<%= simple_form_for[@ride, @review] do |f|%>
  <%= f.input :rating %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "Submit" %>
 <% end %>

app/views/rides/show.html.erb
<div class="margin-from-navbar" id="review" data-ride-id="<%= @ride.id %>">

  <div class="acontainerseven">
    <% if @ride.user == current_user %>
    <h5><%= "You are currently driving home:" %></h5>
    <div class="acontainersix">
      <div id="map"
        style="width: 100%; height: 480px;"
        sytle="align-self-center"
        data-coords="<%= @coords.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{@ride.request.user.nickname}", id: "avatar-driver" %>
    </div>
    <div class="acontainerten">
        <h5><%= @ride.request.user.first_name %> <%= @ride.request.user.last_name %></h5>
        <p><%= @ride.request.user.phone_number %></p>
        <%= link_to "Journey completed", ride_path(@ride), method: :put, class: "btn btn-secondary btn-lg btn-block" %>
      <% else %>
        <%= render 'shared/journey_completed' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 margin-from-navbar" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- <div class="footer">
  <div class="footer-links">
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
 </div>
 <div class="footer-copyright">
    ©GetHome
</div>
</div> -->
 

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_journey_completed.html.erb
<% if @ride.completed? %>
  <div class="acontainerfour">
    <h1><%= "Your journey home has been completed!" %></h1>
  </div>

<div class="acontainertwo">
  <p>We're glad you're now home safely with your car in the driveway.</p>
  <p>Please let us know how your experience with GetHome went. We can't wait to hear from you!</p>
  <%= link_to "Write a Review", new_ride_review_path(@ride), class: "btn btn-info btn-lg btn-block" %>
</div>

<% else %>
  <div id="trip-in-progress">
    <div class="acontainerfive">
      <h4>The Journey Home</h4>
    </div>
    <h5>The driver getting you home is:</h5>
    <div class="acontainereight">
      <div id="map"
        style="width: 100%; height: 450px;"
        sytle="align-self-center"
        data-coords="<%= @coords.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{@ride.user.nickname}", id: "avatar-driver" %>
    </div>
  <div class="acontainernine">
      <h5><%= @ride.user.first_name %> <%= @ride.user.last_name %></h5>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <br>
    <h5>Telephone number:</h5>
      <p><%= @ride.user.phone_number %></p>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-lewagon">
  <%#= link_to root_path, class: "navbar-brand" do %>
    <%#= image_tag "https://www.easylinedrawing.com/wp-content/uploads/2019/07/house_drawing_tutorial.png" %>
    <%# end %>

<!--   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->

  <div class="title <%= 'white' if @navbar_white%>">
     <%= link_to root_path, class: " #{'white' if @navbar_white}" do %> 
     <p>GetHome</p>
    <% end %>
  </div>


  <div id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <!-- <li class="nav-item active"> -->
          <%#= link_to "Home", root_path, class: "nav-link" %>
        <!-- </li>
        <li class="nav-item">
          <%#= link_to "Messages", "#", class: "nav-link" %>
        </li> -->
       <li class="nav-item dropdown">
          <i class="fas fa-bars <%= 'white' if @navbar_white%>" id="navbarDropdown" data-toggle="dropdown"></i>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <p>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></p>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_see_your_trips.html.erb
<% if @request.pending? %>
  <%= link_to "Cancel booking",
          request_path(@request),
          method: :delete,
          data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-lg btn-block", id: 'cancel-booking' %>

<% elsif @request.confirmed? %>
  <br>
  <h6><%= "🎊 Your request has been accepted! 🎊" %></h6>
  <%= link_to "See your driver", ride_path(Ride.find_by(request: request)), class: "btn btn-primary btn-lg btn-block" %>

<% end %>